FT_PIXEL_MODE_NONE =  0
FT_PIXEL_MODE_MONO =  1
FT_PIXEL_MODE_GRAY =  2
FT_PIXEL_MODE_GRAY2 = 3
FT_PIXEL_MODE_GRAY4 = 4
FT_PIXEL_MODE_LCD =   5
FT_PIXEL_MODE_LCD_V = 6
FT_PIXEL_MODE_MAX =   7

FT_OUTLINE_NONE =            0
FT_OUTLINE_OWNER =           1 << 0
FT_OUTLINE_EVEN_ODD_FILL =   1 << 1
FT_OUTLINE_REVERSE_FILL =    1 << 2
FT_OUTLINE_IGNORE_DROPOUTS = 1 << 3
FT_OUTLINE_HIGH_PRECISION =  1 << 8
FT_OUTLINE_SINGLE_PASS =     1 << 9

FT_GLYPH_FORMAT_NONE = 0
FT_GLYPH_FORMAT_COMPOSITE =  1668246896
FT_GLYPH_FORMAT_BITMAP =     1651078259
FT_GLYPH_FORMAT_OUTLINE =    1869968492
FT_GLYPH_FORMAT_PLOTTER =    1886154612

FT_ENCODING_NONE = 0
FT_ENCODING_MS_SYMBOL =      1937337698
FT_ENCODING_UNICODE =        1970170211

FT_ENCODING_SJIS =           1936353651
FT_ENCODING_GB2312 =         1734484000
FT_ENCODING_BIG5 =           1651074869
FT_ENCODING_WANSUNG =        2002873971
FT_ENCODING_JOHAB =          1785686113

FT_ENCODING_ADOBE_STANDARD = 1094995778
FT_ENCODING_ADOBE_EXPERT =   1094992453
FT_ENCODING_ADOBE_CUSTOM =   1094992451
FT_ENCODING_ADOBE_LATIN_1 =  1818326065
FT_ENCODING_OLD_LATIN_2 =    1818326066
FT_ENCODING_APPLE_ROMAN =    1634889070

FT_FACE_FLAG_SCALABLE =         1L << 0
FT_FACE_FLAG_FIXED_SIZES =      1L << 1
FT_FACE_FLAG_FIXED_WIDTH =      1L << 2
FT_FACE_FLAG_SFNT =             1L << 3
FT_FACE_FLAG_HORIZONTAL =       1L << 4
FT_FACE_FLAG_VERTICAL =         1L << 5
FT_FACE_FLAG_KERNING =          1L << 6
FT_FACE_FLAG_FAST_GLYPHS =      1L << 7
FT_FACE_FLAG_MULTIPLE_MASTERS = 1L << 8
FT_FACE_FLAG_GLYPH_NAMES =      1L << 9
FT_FACE_FLAG_EXTERNAL_STREAM =  1L << 10
FT_FACE_FLAG_HINTER =           1L << 11

FT_STYLE_FLAG_ITALIC =          1 << 0
FT_STYLE_FLAG_BOLD =            1 << 1

FT_SIZE_REQUEST_TYPE_NOMINAL =  0
FT_SIZE_REQUEST_TYPE_REAL_DIM = 1
FT_SIZE_REQUEST_TYPE_BBOX =     2
FT_SIZE_REQUEST_TYPE_CELL =     3
FT_SIZE_REQUEST_TYPE_SCALES =   4
FT_SIZE_REQUEST_TYPE_MAX =      5

FT_LOAD_DEFAULT =                     0
FT_LOAD_NO_SCALE =                    1 << 0
FT_LOAD_NO_HINTING =                  1 << 1
FT_LOAD_RENDER =                      1 << 2
FT_LOAD_NO_BITMAP =                   1 << 3
FT_LOAD_VERTICAL_LAYOUT =             1 << 4
FT_LOAD_FORCE_AUTOHINT =              1 << 5
FT_LOAD_CROP_BITMAP =                 1 << 6
FT_LOAD_PEDANTIC =                    1 << 7
FT_LOAD_IGNORE_GLOBAL_ADVANCE_WIDTH = 1 << 9
FT_LOAD_NO_RECURSE =                  1 << 10
FT_LOAD_IGNORE_TRANSFORM =            1 << 11
FT_LOAD_MONOCHROME =                  1 << 12
FT_LOAD_LINEAR_DESIGN =               1 << 13
FT_LOAD_SBITS_ONLY =                  1 << 14
FT_LOAD_NO_AUTOHINT =                 1 << 15

FT_RENDER_MODE_NORMAL = 0
FT_RENDER_MODE_LIGHT =  1
FT_RENDER_MODE_MONO =   2
FT_RENDER_MODE_LCD =    3
FT_RENDER_MODE_LCD_V =  4
FT_RENDER_MODE_MAX =    5

FT_KERNING_DEFAULT =    0
FT_KERNING_UNFITTED =   1
FT_KERNING_UNSCALED =   2

FT_SUBGLYPH_FLAG_ARGS_ARE_WORDS =      1
FT_SUBGLYPH_FLAG_ARGS_ARE_XY_VALUES =  2
FT_SUBGLYPH_FLAG_ROUND_XY_TO_GRID =    4
FT_SUBGLYPH_FLAG_SCALE =               8
FT_SUBGLYPH_FLAG_XY_SCALE =           64
FT_SUBGLYPH_FLAG_2X2 =               128
FT_SUBGLYPH_FLAG_USE_MY_METRICS =    512

FT_GLYPH_BBOX_UNSCALED  = 0
FT_GLYPH_BBOX_SUBPIXELS = 0
FT_GLYPH_BBOX_GRIDFIT   = 1
FT_GLYPH_BBOX_TRUNCATE  = 2
FT_GLYPH_BBOX_PIXELS    = 3


FT_ORIENTATION_TRUETYPE =   0
FT_ORIENTATION_POSTSCRIPT = 1
FT_ORIENTATION_FILL_RIGHT = 0
FT_ORIENTATION_FILL_LEFT =  1
FT_ORIENTATION_NONE =       2

